version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_REACT_APP_API_URL=http://localhost:5000
    ports:
      - "5173:80"
    environment:
      - VITE_REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FRONTEND_URL=http://localhost:5173
    networks:
      - mern-network


networks:
  mern-network:
    driver: bridge